### ISSUE TITLE
Authentication Token ?

### ISSUE THREAD

**Issue by stijink** [BabDev/Transifex-API#8]
Hi,

is there a way to use an authentication token instead of an username/password for authentication ?

Thanks,
Stephan

**Comment by ot2sen** [comment]
Looks like they added token since I last checked their docs.
https://docs.transifex.com/api/introduction

Says: Use 'api' as username and your authentication token as password.

**Comment by mbabker** [comment]
Ya, the way that docs page reads you replace your username with "api" and your password with the authentication token.  Shouldn't need any other change on this side.

**Comment by stijink** [comment]
Ah, you're right. I just compared your code closely to my guzzle-only implementation. And indeed, it's that simple. Sorry for overseeing that.
