### ISSUE TITLE
base_url is not taken into account on a guzzle request

### ISSUE THREAD

**Issue by stijink** [BabDev/Transifex-API#9]
Options i explicitly set:
- api.username
- api.password
- base_url

```php
$transifex = new Transifex([
    'api.username' => 'xxx',
    'api.password' => 'xxx', 
    'base_url' => 'https://www.transifex.com'
]);
```

Note: The error also occurs if i not explicitly set the base_url

Then i make the following call:
```php
$resources = $transifex->get('resources')
$resources->getResource('project', 'resource-name');
````

I get the following error:
```
cURL error 3: <url> malformed (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)
```

If i dump the $uri in `/vendor/guzzlehttp/guzzle/src/Client.php::requestAsync` i get the following output. Note that the scheme and the host is missing:
```
GuzzleHttp\Psr7\Uri {#73
  -scheme: ""
  -userInfo: ""
  -host: ""
  -port: null
  -path: "/api/2/project/project/resource/resource-name/"
  -query: ""
  -fragment: ""
}
```

**Comment by mbabker** [comment]
Fixed and new tag created.

**Comment by mbabker** [comment]
You know, I just realized.  This actually didn't need a fix.  The option name is `base_uri`, not `base_url`.  But, if/when [PSR-18](https://github.com/php-fig/fig-standards/tree/master/proposed/http-client/) is accepted, the next major version would rely on that versus a specific adapter and I couldn't rely on the Guzzle internals to apply the base URL, so putting the base URL logic (back) into my code would have to happen sooner or later.

**Comment by stijink** [comment]
Thanks. I'll give it a try :-)
